# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logis_fe_prov <- function(Y, Z, n_prov, gamma, beta, backtrack = 0L, max_iter = 10000L, bound = 10.0, tol = 1e-5, message = TRUE) {
    .Call(`_srrFE_logis_fe_prov`, Y, Z, n_prov, gamma, beta, backtrack, max_iter, bound, tol, message)
}

logis_BIN_fe_prov <- function(Y, Z, n_prov, gamma, beta, parallel = 1L, threads = 1L, tol = 1e-8, max_iter = 10000L, bound = 10.0, message = TRUE, backtrack = FALSE) {
    .Call(`_srrFE_logis_BIN_fe_prov`, Y, Z, n_prov, gamma, beta, parallel, threads, tol, max_iter, bound, message, backtrack)
}

logis_firth_prov <- function(Y, Z, n_prov, gamma, beta, n_obs, m, parallel = 1L, threads = 1L, tol = 1e-8, max_iter = 10000L, bound = 10.0, message = TRUE, backtrack = FALSE) {
    .Call(`_srrFE_logis_firth_prov`, Y, Z, n_prov, gamma, beta, n_obs, m, parallel, threads, tol, max_iter, bound, message, backtrack)
}

wald_covar <- function(Y, Z, n_prov, gamma, beta, indices, null, alpha) {
    .Call(`_srrFE_wald_covar`, Y, Z, n_prov, gamma, beta, indices, null, alpha)
}

